[#]>B A S I C   L E S S O N S
(c) 2002, Alexey Kazantsev

[#] df  jk
fffjjj ffjfj jffjj fjfjf jjfjf fj fjf fjffj jfjfj jf jfj dddjjj ddjdj jddjj djdjd jjdjd dj df jd djddj jdjdj dj dfd fd jd jfd jdf kkkddd kkdkd dkkdd kdkdk ddkdk kf jdk kj kdkkd dkdkd kj dk jdk fkjd ffkfk kffkk fkfkf kf jfk kkfkf fkffk kfkfk fk fdk fkj dfk ddfdf fddff kf dfd ffdfd jd fdd fkd jjkjk kjjkk jk jdk jkjkj kj fkj djdfk jfkkd jdjkf fjddk fkfdj kdjjf kfkjd dkffj dj fdd jk dfd jdk jd kf djfk

[#] as  l;
ssslll sslsl lssll slsls llsls sl ls lsl slssl lslsl lf kl lsd sk sf sl fls dll jl js aaalll aalal laall alala llala la lak all alaal lalal ad adj lda alf alfa sal flak ;;;aaa ;;a;a a;;aa ;a;a; aa;a; ala; dak; kaka; ;a;;a a;a;a add jaffa; da aka dad; ss;s; ;ss;; s;s;s ;;s;s fss; js; s;ss; ;s;s; ass; lass; aasas saass ask sla asasa ssasa jsa sad sas ll;l; ;ll;; fl; l;l;l ;;l;l fla; fld; alas; ls;;a lal;s slaa; s;sal ;alls ;s;la a;ssl als fall dak das jad; adsl; skald; alk flask; falls adds fad; lass asks lad; sad dad ass as a flak;

[#] vb  nm
bbbnnn bbnbn nbbnn bnbnb nnbnb nan bab blab lan ban jan bnbbn nbnbn abba anna jab nab bass bask bad fan lab fab dab nb dan bland blank and bank vvvnnn vvnvn nvvnn vnvnv nnvnv val van vnvvn nvnvn java vs vb vandal vas vj lava naval dvd mmmvvv mmvmv vmmvv mvmvm vvmvm mak malm mvmmv vmvmv am lam mass mamma small mask jam sms jvm bbmbm mbbmm bmbmb mmbmb amb lamb bmbbm mbmbm bam jamb mamba vvbvb bvvbb vbvbv bvds vnnmnm mnnmm man mmnmn manna nam vnvbm nbmmv nvnmb bnvvm bmbvn mvnnb mbmnv vmbbn band van kvass lambda dvd nan jams small bank vandal

[#] tg  yh
tttyyy ttyty yttyy tytyt yytyt my tad tytty ytyty talk fat yak sat mat nat yam yd nasty navy tasty may tatty lastly gggyyy ggygy yggyy gygyg yygyg baggy gyggy ygygy gad slang lag jaggy gadfly mangy gabby hhhggg hhghg ghhgg hghgh gghgh hash ghat hghhg ghghg has handy dash aghast tthth htthh ththt hhtht that bath thtth hthth thank myth ggtgt tggtt gat gtgtg ttgtg tang yyhyh hyyhh shy yhyhy hhyhy hymn gygth ythhg ygyht tyggh thtgy hgyyt hthyg ghtty gyttja ghastly shaggy laystall fatly tansy gym lay by taffy sly yank tat many thanks

[#] er  ui
rrruuu rruru urruu rurur uurur radar ugly rug rurru ururu rub rural aura drum jury burn hurry guru ruth eeeuuu eeueu ueeuu eueue uueue sun eye vugh bevel gun eueeu ueueu leu lues neutral hue due fuel rueful guest heugh iiieee iieie eiiee ieiei eeiei evil fire ieiie eieie tie lie die tried ivied field reign rriri irrii ririr iirir irk sir rirri iriri iris trim bird rile girl firm eerer reerr there erere rrere here nerve uuiui iuuii suit guide uiuiu iiuiu build ruins eueri uriie ueuir rueei rireu ieuur iriue eirru vigil duke merit germinative guerilla mute university gurgle true rule during survey remain renumber

[#] qw  op
wwwooo wwowo owwoo wowow oowow wow low now owe woe wowwo owowo row owner wood woke worm wolf world how work qqqooo qqoqo oqqoo qoqoq ooqoq qua iq qoqqo oqoqo equal quad quake quiet quit unique queen quay quod quoin quorum quota quotha pppqqq ppqpq qppqq pqpqp qqpqp equip up pqppq qpqpq pal pig pen pan pap pepper pepsi rap vip tape pair palp opaque wwpwp pwwpp wpwpw ppwpw paw pow wpwwp pwpwp wrap wipe weep whip wimp qqwqw wqqww sow qwqwq wwqwq query oopop poopp pop opopo ppopo opel prop qoqwp owppq oqopw woqqp wpwqo pqoow pwpoq qpwwo quid pro quo equator whore purple equivoke whole power opaque

[#] xc  , .
ccc,,, cc,c, ,cc,, c,c,c ,,c,c cd, cop, cow, calc, c,cc, ,c,c, cap, cup, cut, copy, cake, come, accept, cock, clock, cache, cackle, cluck, clinic, click cancel xxx,,, xx,x, ,xx,, x,x,x ,,x,x xxl, xml, mix, six, x,xx, ,x,x, fax, fox, box, vox, dux, excel, onyx, exile ...xxx ..x.x x..xx .x.x. xx.x. lex. cox. .x..x x.x.x xmas. xerox. oxy. extreme. exact, relax, cc.c. .cc.. c.c.c ..c.c .ca .ch .com c.cc. .c.c. ch. ck. civ. con. xxcxc cxxcc calyx xcxcx ccxcx coax coccyx ,,.,. .,,.. ex., ,.,., ..,., etc., x,xc. ,c..x ,x,.c c,xx. c.cx, .x,,c .c.,x x.cc, p.c., i.e., e.g., www.pix.com, a.m., unix.com, xxx.com

[#] z ! ? /
zzz/// zz/z/ /zz// z/z/z //z/z jazz zoo/zone z/zz/ /z/z/ zero zap/zombie mezzo lazy/hazy gaze zoom/gizmo, crazy zigzag/puzzle !!!/// !!/!/ /!!// !/!/! //!/! hello/hi! go! !/!!/ /!/!/ welcome! thanks! bazooka! squeeze! ???!!! ??!?! !??!! ?!?!? !!?!? how?! who? ?!??! !?!?! toxic!? why? azure? ok! zz?z? ?zz?? z?z?z ??z?z oz? fuzzy zebra? z?zz? ?z?z? zeal? zinc? !!z!z z!!zz zip! !z!z! zz!z! zing! //?/? ?//?? yes/no? /?/?/ ??/?/ zephyr/pizza? !/!z? /z??! /!/?z z/!!? z?z!/ ?!//z ?z?/! !?zz/ zenith/frozen waltz tzar/lizzie pkunzip.zip? new! all right! what? which? are you here? good luck/bye!

[#] ; : -
;;;::: ;;:;: :;;:: ;:;:; ::;:; a:b; c:d; ;:;;: :;:;: City: Color: Password: ;) :) e; f; g; ;;;--- ;;-;- -;;-- ;-;-; --;-; so-so; back-up; ;-;;- -;-;- about-face; yo-yo; hara-kiri ;-) ::-:- -::-- :-:-: --:-: chin-chin :) :-::- -:-:- fie-fie: you-know-what :-) ;;:-; :;-:: -;--: ping-pong ;-:;: ;-:-; -:-;: month: June; ;:-:;- ;-:-;: :-;-:; Coca-cola; name: Alice; hobby: music; etc; case: break; continue; Bye-bye

[#] Alphabetic test
fall jam dash kid ska lad alf bank navy valid man gal ham talk yak rutty urn elf is wolf oven quasi pet xxl cot zone abcdefghijklmnopqrstuvwxyz fife jojoba doddle kick suss label aka bob nine vulva memo guggle hah totality yellowy river unused eke ivied willow oboe quark prep xerox clack zigzag zyxwvutsrqponmlkjihgfedcba

[#] Short words
hay heir harp half hang hack hex high echo earn elan eddy edit obit oboe obey owl oak okie dokey down duty dux dixy doxy xmas xtal nix next note name nape nail snap spar step slow shot shit qua quay quad quod quit pack pray pure pig pixy push rush rue rock rose rich ring main mad male melt milk make zero zest zonk zoom zinc zing year yelp ywis your chip char cut chut coxy cow kale ken knap keep keck kiwi with wind wick woke wont void volt vole vote vita vox vug very jerk joke jack jab job jamb jeep girl glue gold grow good luck lake lid lie lex live love

[#] Long words
allowable absolute black bonus bicycle expressive eating fortune finish frequency fuzzy imperial include kilobyte obtain throw tutor cherry casino cinema cajole candle rubric rover rigor unbound unique vampire velvet vogue yearly zombie zippy quack quick quake queen query quorum quadruple xenon xerox xistor xiphoid xylogen xanthoxylone nixie nothing network neighbour window weight world winch whose white south sounding submarine jumbo justify journey government paradox penalty paving pepsi guano apes memento mori

[#] CAPITAL letters
Fred Fuji Jerry January Dick Doom Kate Ken Sony Stamina Lily Lady April Alf Nick NB Victor Val Bob Bill Yes YOB Tom Tim Henry Hamlet Grace Glen Uncle Unreal Romeo RIP Irene ICQ Eve Earth Mylene MIB Chris Charles Oval Office Walt Wales Peg PS Quake Queen Xmas XXL Zaire Zorro Felix John December Kit Sam Luke Alex November VIP Boston Yahoo Ted Helen Gates UFO Rose Ira Ed May Carol October WC Pol Quantum XML Zanzibar Antonio Vivaldi Nino Rota Bon Jovi Led Zeppelin Pink Floyd Genesis Vaya Con Dios Enya

[#]<

[#]>C O M B I N A T I O N S

[#] Combinations 1
th the they then them there their that this wh why who whom when where what while ea eat east tear read head beat deal leaf ed bed med led red tired shed liked armed moved en pen den ten often listen given taken even frozen happen broken er her ever over river after enter under order biker joker ar car bar mar oral polar solar star or for nor author actor major motor tutor sailor al pal gal dual usual rural royal vital total ay say day way ray pay lay may ly sly fly ugly only rally reply apply badly ry try cry dry fry very weary carry gh high sigh weigh bough though ew new few pew blew view ow now how low row sow yellow

[#] Combinations 2
un un un un un un unit uncle under unable unlock ing ing ing ing ing ing ping wing bring thing doing going ght ght ght ght ght ght night right weight straight thought ish ish ish ish ish dish wish finish publish longish ist ist ist ist ist ist fist list exist consist ous ous ous ous ous ous nous famous nervous house age age age age age age page stage manage voyage Garbage ant ant ant ant ant ant rant distant giant variant ment ment ment ment ment ment moment ferment equipment tion tion tion tion tion tion action option edition mention condition citation ture ture ture ture ture ture future culture nature picture

[#] Parts of speech 1
the the the the they they they they they they there there there there there there at at at at that that that that that that what what what what what what is is is is his his his his his his this this this this this this it it it it in in in in to to to to into into into into into into an an an an can can can can can can and and and and and and as as as as was was was was was was has has has has has has had had had had had had have have have have have have be be be be been been been been been been up up up up on on on on upon upon upon upon upon upon upon if if if if of of of or or or or for for for for for for from from from from from from who who who who who why why why why why which which which which which which which which which which we we we we were were were were were were are are are are are are

[#] Parts of speech 2
isn't isn't isn't isn't aren't aren't aren't aren't can't can't can't can't wasn't wasn't wasn't wasn't weren't weren't weren't weren't haven't haven't haven't haven't hasn't hasn't hasn't hasn't hadn't hadn't hadn't hadn't won't won't won't won't don't don't don't don't didn't didn't didn't didn't This's This's This's This's They're They're They're They're You're You're You're You're It's It's It's It's I'm I'm I'm I'm I'll I'll I'll I'll What's What's What's What's

[#]<

[#]>D I G I T S   &   S Y M B O L S

[#] 56  78
666777 66767 76677 67676 77676 67667 76767 555777 55757 75577 57575 77575 57557 75757 576 75 67 657 888555 88585 58855 85858 55858 85885 58585 685 758 78 66868 86688 68686 88686 68668 86868 868 586 7568 55656 65566 Effel 65 56565 66565 77878 87788 867 758 78787 88787 57568 76885 75786 67558 68657 85776 86875 58667

[#] 34  90
444999 44949 94499 49494 99494 74 59 49449 94949 964 849 333999 33939 93399 39393 99393 83 49 39339 93939 593 739 000333 00303 30033 03030 33030 40 93 03003 30303 360 830 44040 04400 40404 00404 Error 404 40440 04040 Apollo 440 33434 43344 374 km 39 m 34343 44343 99090 09900 940 kg 90909 00909 39340 94003 93904 49330 40439 03994 04093 30449

[#] 12  -=
222--- 22-2- -22-- 2-2-2 --2-2 20 8-2 2-22- -2-2- 111--- 11-1- -11-- 1-1-1 --1-1 01 1-9 1-11- -1-1- 1-2-3 ===111 ==1=1 1==11 =1=1= 11=1= 1-1=0 2-1=1 =1==1 1=1=1 1 byte = 8 bits 22=2= =22== 2=2=2 ==2=2 52-81=-29 2=22= =2=2= 11212 21122 71 82 12121 22121 --=-= =--== -2-1=-3 -=-=- ==-=- 1-12= -2==1 -1-=2 2-11= 2=21- =1--2 =2=-1 1=22- 7-5=2 Y2K, Blink 182, 911, U-96.mp3

[#] Numbers 01-99
01 08 03 07 05 09 04 06 02 10 80 30 70 50 90 40 60 20 14 17 15 19 13 18 12 10 16 41 71 51 91 31 21 01 25 29 23 27 21 20 24 28 26 52 92 72 12 02 42 82 62 35 38 31 30 34 37 32 39 36 53 83 13 03 43 73 23 93 63 41 48 46 40 42 47 45 49 43 14 84 64 04 24 74 54 94 34 52 58 54 50 53 57 51 59 56 25 85 45 05 35 75 15 95 65 68 61 67 64 69 62 60 63 56 86 16 76 64 96 26 06 36 72 78 74 70 75 79 71 76 73 27 87 47 07 57 97 17 67 37 82 80 85 89 83 87 81 84 86 28 08 58 98 38 78 18 48 68 92 97 94 90 96 98 93 91 95 29 79 49 09 69 89 39 19 59

[#] % ^  & *
^^^&&& ^^&^& &^^&& ^&^&^ &&^&^ a&b, c&d, 3^8, 9^7 ^&^^& &^&^& a&b^j^k&l, drag & drop %%%&&& %%&%& &%%&& %&%&% &&%&% 75% 50% 15% 0% %&%%& &%&%& 10% & 80% 5% ***%%% **%*% %**%% *%*%* %%*%* 5*8=40 4*8 *%**% %*%*% 5*39% 28*2 85*8% ^^*^* *^^** ^*^*^ **^*^ 3*2^7 ^*^^* *^*^* 8^2*6 %%^%^ ^%%^^ 30% %^%^% ^^%^% 7^2 &&*&* *&&** 3*4 &*&*& **&*& cash & carry %&%^* &^**% &%&*^ ^&%%* ^*^%& *%&&^ *^*&% %*^^& Erase & Rewind

[#] # $  ( )
$$$((( $$($( ($$(( $($($ (($($ $84 $0 $($$( ($($( $74 $2.94 $8.49 ###((( ##(#( (##(( #(#(# ((#(# #96 #43 #75 #(##( (#(#( #93 #13 #837 ))#)# #))## )#)#) ##)#) (#9) (#03) )#))# #)#)# (#93) (#3) (#01) $$)$) )$$)) $)$)$ ))$)$ ($04) ($94) $)$$) )$)$) ($74) ($8) ##$#$ $##$$ #73 #$#$# $$#$# $04 (()() )(()) (Yes) ()()( ))()( (A) (B) #(#$) ($))# (#()$ $(##) $)$#( )#(($ )$)(# #)$$(

[#] ! @  _ +
@@@___ @@_@_ _@@__ @_@_@ __@_@ my_mail@domen.com @_@@_ _@_@_ a_b@aol.com !!!___ !!_!_ _!!__ !_!_! __!_! Hi! I_love_you! !_!!_ _!_!_ +++!!! ++!+! !++!! +!+!+ !!+!+ 1+1=2! 2+2=4! +!++! !+!+! 3+2=5! 5+2=7! @@+@+ +@@++ @+@+@ ++@+@ 47+38 @+@@+ +@+@+ info@mail.com !!@!@ @!!@@ Wow! !@!@! @@!@! @:-) ;@) __+_+ +__++ _accent_ _+_+_ ++_+_ 4+3 !_!@+ _@++! _!_+@ @_!!+ @+@!_ +!__@ +@+_! !+@@_ b_g@microsoft.com!

[#] ` ~  \ |
```\\\ ``\`\ \``\\ `\`\` \\`\` `\``\ \`\`\ ~~~\\\ ~~\~\ \~~\\ ~\~\~ \\~\~ ~\~~\ \~\~\ |||~~~ ||~|~ ~||~~ |~|~| ~~|~| |~||~ ~|~|~ ``|`| |``|| `|`|` ||`|` `|``| |`|`| ~~`~` `~~`` ~`~`~ ``~`~ \\|\| |\\|| \|\|\ ||\|\ ~\~`| \`||~ \~\|` `\~~| `|`~\ |~\\` |`|\~ ~|``\

[#] [ ] { }
[[[]]] [[][] ][[]] [][][ ]][][ [C:\Temp\] [][[] ][][] [a,b] [c,d] [3;8] {{{]]] {{]{] ]{{]] {]{]{ ]]{]{ {:-] {]{{] ]{]{] {;-] }}}{{{ }}{}{ {}}{{ {5;4} }{}{} {{}{} {6;2} }{}}{ {}{}{ {3,4} {48,91} [[}[} }[[}} [}[}[ }}[}[ [}[[} }[}[} [1,2} {{[{[ [{{[[ {[{[{ [[{[{ {3,4] ]]}]} }]]}} ]}]}] }}]}] {]{[} ][}}{ ]{]}[ []{{} [}[{] }{]][ }[}]{ {}[[] [C:\Progra~1\] H1 { color:red; }

[#] < >
xxx<<< Xx<x< <xx<< x<x<x <<x<x x<xX< <x<x< zzz<<< Zz<z< <zZ<< z<z<z <<z<z z<zZ< <z<z< >>z>z z>>Zz >z>z> Zz>z> >z>>z z>z>z Xx>x> >xX>> x>x>x >>x>x x>xX> >x>x> <<><> ><<>> <><>< >><>< z<Zx> <x>>z <z<>x x<Zz> <><,. >,..< x>Xz< >z<<x >x><z z>xX< ><>., ,><<.

[#] All symbols
3#3#3 |#|#|# #3 #23 #83 )0)0) :-0 ;) 2@2@2 {@{@{@ user@hotmail.com; 9(9(9 :-9 ;-( 4$4$4 _$_$_$ $4 $1.40 $4.99 7&7&7 &^&^&^ wash & go, black & white 6^6^6 2^8 9^6; 5%5%5 }%}%}% 50% 25% 0%; 8*8*8 *<*<*> *.mp3 6*8=48 1!1!1 !>!>!< OK! Hi! How do you do? 4/2=2 8/2=4 3+2=5 1+3=4 1+2+3+4+5=15 Are you ready? Really? [`[`[` ]~]~]~ \#\#\# _@_@_%_% login@aol.com; `}`}`} #*#*_@_| \~\~{~{ [^[^]^]^ _#_$_%\@ [@_|`\* 5-!=? 9+3-4 _3(3)_ {%&#&@} $]$~_ @&$&*| a>=b>=c ~$\[#&` _@_~\` 1<3<7 5/3 7/4 9/2 %`&~|~ ^@_~}` &$~[|` \`[~*@ F(x)<=F[y]>=F{z}

[#]<

[#]>S P E C I A L   L E S S O N S

[#] Smiles :-)
:) :-) ;-) :=) ;=) :o) ;o) :-/ ;-\ B=) B-) 8-) :-P :-b :=D :-o <:-) ;^) &:-) @;-) %-) >:-( :-@ 8:-) :-{) :-{} {:-) :-7 :-9 :=] ;( :-( ;-0 :-| :( ;-( :o( ;o( ;=( B-| B-( 8=) :-)))))

[#] HTML
/#/#/# #'#'#' %"%"%" %&%&%& _/_/_/ ;@;@;@ -:-:-: <!<!<! >=>=>= ="#993366" ='30%' <a href=mailto:x@y.z> <html> <head><title>Welcome</title></head> <body bgcolor=#0F0F0F leftmargin=0><p align="right">Hi, people!</p> <table border="0" width=76%><tr><td>&nbsp;</td></tr></table> <div align='center' width='50%'><p style="border:1px solid #339966">&lt; &nbsp; &quot; &amp; &gt; </p></div> <!-- comments --> <hr width=82% color="#38f7e9"><a href="http://staminapro.com" target=_blank>Home</a></body></html>

[#]-

[#] NumPad (digits only)
5466¶4560¶45405¶5606¶5405¶6504¶4605¶46460¶5880¶580486¶80688¶4522¶5224¶02286¶4022¶8546¶0822¶8508¶26022¶8077¶508787¶04776¶0885¶7027¶70775¶6075¶7467¶2095¶9959¶09699¶4902¶929299¶80658¶9980¶4994¶90225¶8906¶77290¶115¶15102¶1151106¶1411¶480¶9119¶11076¶15810¶491¶851¶06842¶06789¶10461¶210¶115¶811¶7033¶5334¶603¶351¶30¶3642¶033¶5833¶031¶633031¶3130348¶609¶941387¶0564¶023203¶4602¶790¶3180¶513076¶704¶6805050¶1000¶50807¶6109¶00080¶88192¶2001¶2002¶1978¶1700¶6810¶4058¶6506¶06505¶0030¶2010¶1834¶5123¶0234¶07764¶8127¶703577¶6276¶7672¶712¶97437

[#] NumPad
7/8/9¶5/6/4¶3/1/2¶9/5/1¶87/46/32¶8*7*9¶5*6*4¶2*1*3¶7*5*3¶89*46*12¶7-9-8¶5-6-4¶3-1-2¶8-4-3¶79-65-20¶9+7+8¶5+4+6¶2+1+3¶7+6+2¶98+54+30¶7.98¶5.64¶3.12¶0.951¶3.14¶7/5*3-1+3.08¶76+84-943+80+215-30-51¶286/14*9*372/84*50/306¶.315*.486+1.509-.75/6.02¶45+5.18+862-.75-13/.94/26*3.14*80+1.27*50-6.52/9

[#]<

[#]-

[#]>S T U P I D   L E S S O N S

[#] d f j k
fffjjj ffjfj jffjj fjfjf jjfjf fjffj jfjfj dddjjj ddjdj jddjj djdjd jjdjd djddj jdjdj kkkddd kkdkd dkkdd kdkdk ddkdk kdkkd dkdkd fffkkk ffkfk kffkk fkfkf kkfkf fkffk kfkfk ddfdf fddff dfdfd ffdfd jjkjk kjjkk jkjkj kkjkj djdfk jfkkd jdjkf fjddk fkfdj kdjjf kfkjd dkffj

[#] a s l ô
ssslll sslsl lssll slsls llsls slssl lslsl aaalll aalal laall alala llala alaal lalal ôôôaaa ôôaôa aôôaa ôaôaô aaôaô ôaôôa aôaôa sssôôô ssôsô ôssôô sôsôs ôôsôs sôssô ôsôsô aasas saass asasa ssasa llôlô ôllôô lôlôl ôôlôl alasô lsôôa lalôs slaaô sôsal ôalls ôsôla aôssl

[#] v b n m
bbbnnn bbnbn nbbnn bnbnb nnbnb bnbbn nbnbn vvvnnn vvnvn nvvnn vnvnv nnvnv vnvvn nvnvn mmmvvv mmvmv vmmvv mvmvm vvmvm mvmmv vmvmv bbbmmm bbmbm mbbmm bmbmb mmbmb bmbbm mbmbm vvbvb bvvbb vbvbv bbvbv nnmnm mnnmm nmnmn mmnmn vnvbm nbmmv nvnmb bnvvm bmbvn mvnnb mbmnv vmbbn 

[#] g t z h
tttzzz ttztz zttzz tztzt zztzt tzttz ztztz gggzzz ggzgz zggzz gzgzg zzgzg gzggz zgzgz hhhggg hhghg ghhgg hghgh gghgh hghhg ghghg ttthhh tthth htthh ththt hhtht thtth hthth ggtgt tggtt gtgtg ttgtg zzhzh hzzhh zhzhz hhzhz gzgth zthhg zgzht tzggh thtgz hgzzt hthzg ghttz 

[#] e r u i
rrruuu rruru urruu rurur uurur rurru ururu eeeuuu eeueu ueeuu eueue uueue eueeu ueueu iiieee iieie eiiee ieiei eeiei ieiie eieie rrriii rriri irrii ririr iirir rirri iriri eerer reerr erere rrere uuiui iuuii uiuiu iiuiu eueri uriie ueuir rueei rireu ieuur iriue eirru 

[#] q w o p
wwwooo wwowo owwoo wowow oowow wowwo owowo qqqooo qqoqo oqqoo qoqoq ooqoq qoqqo oqoqo pppqqq ppqpq qppqq pqpqp qqpqp pqppq qpqpq wwwppp wwpwp pwwpp wpwpw ppwpw wpwwp pwpwp qqwqw wqqww qwqwq wwqwq oopop poopp opopo ppopo qoqwp owppq oqopw woqqp wpwqo pqoow pwpoq qpwwo 

[#] x c , .
ccc,,, cc,c, ,cc,, c,c,c ,,c,c c,cc, ,c,c, xxx,,, xx,x, ,xx,, x,x,x ,,x,x x,xx, ,x,x, ...xxx ..x.x x..xx .x.x. xx.x. .x..x x.x.x ccc... cc.c. .cc.. c.c.c ..c.c c.cc. .c.c. xxcxc cxxcc xcxcx ccxcx ,,.,. .,,.. ,.,., ..,., x,xc. ,c..x ,x,.c c,xx. c.cx, .x,,c .c.,x x.cc, 

[#] & y - §
yyy--- yy-y- -yy-- y-y-y --y-y y-yy- -y-y- &&&--- &&-&- -&&-- &-&-& --&-& &-&&- -&-&- §§§&&& §§&§& &§§&& §&§&§ &&§&§ §&§§& &§&§& yyy§§§ yy§y§ §yy§§ y§y§y §§y§y y§yy§ §y§y§ &&y&y y&&yy &y&y& yy&y& --§-§ §--§§ -§-§- §§-§- &-&y§ -y§§& -&-§y y-&&§ y§y&- §&--y §y§-& &§yy- 

[#] ; ú ä ò
úúúäää úúäúä äúúää úäúäú ääúäú úäúúä äúäúä ;;;äää ;;ä;ä ä;;ää ;ä;ä; ää;ä; ;ä;;ä ä;ä;ä òòò;;; òò;ò; ;òò;; ò;ò;ò ;;ò;ò ò;òò; ;ò;ò; úúúòòò úúòúò òúúòò úòúòú òòúòú úòúúò òúòúò ;;ú;ú ú;;úú ;ú;ú; úú;ú; ääòäò òääòò äòäòä òòäòä ;ä;úò äúòò; ä;äòú úä;;ò úòú;ä ò;ääú òúòä; ;òúúä 

[#]   ı á
ııı ıı ııı ıı ııı ıı ııı ııı ıı ııı ıı ııı ıı ııı ááá ááá áá ááá áá ááá áá ááá áá ááá áá ááá áá ááá     ııáıá áııáá ıáıáı ááıáı ıá ıáá ııá ıá áı áıı ááı áı

[#] š è í é
èèèííí èèíèí íèèíí èíèíè ííèíè èíèèí íèíèí šššííí ššíší íššíí šíšíš ííšíš šíšší íšíší éééššš ééšéš šééšš éšéšé ššéšé éšééš šéšéš èèèééé èèéèé éèèéé èéèéè ééèéè èéèèé éèéèé ššèšè èššèè šèšèš èèšèš ííéíé éííéé íéíéí ééíéí šíšèé íèééš íšíéè èíššé èéèší éšííè éèéíš šéèèí 

[#] + ¾ =
+++¾¾¾ ++¾+¾ ¾++¾¾ +¾+¾+ ¾¾+¾+ +¾++¾ ¾+¾+¾ +++=== ++=+= =++== +=+=+ ==+=+ +=++= =+=+= ¾¾¾=== ¾¾=¾= =¾¾== ¾=¾=¾ ==¾=¾ ¾=¾¾= =¾=¾= ++¾=+ ¾+=¾¾ =+==¾ +=¾+¾ +=¾=+ =¾=+¾ +¾=¾+= +=¾=+¾ ¾=+=¾+ 

[#]<

[#]<-------------------------------->

