Sídlo redakcie: Kutlíkova 17, Blok B/1306, Bratislava Zodp.
Vydáva: InfoDigest P.
Ïalšie šírenie tıchto materiálov, ako aj šírenie InfoDigestu, je moné len so súhlasom vydavate¾a a uvedením zdroja.
Nová technológia nazvaná Rush s¾ubuje zmenšenie ve¾kosti grafiky o 85 a 95 percent!
Rush technológiu vyvinula kanadská firma RMX Technologies.
Vyuíva špeciálny softvérovı jazyk na spracúvanie objemnıch obrázkov do štíhlych kódov, ktoré obsahujú všetky podrobnosti potrebné na rekonštrukciu originálu.
Technológia najskôr vytvorí svoj kód a potom dáta skomprimuje.
Na stránkach vırobcu sú vystavené plug-in moduly pre webovské prehliadaèe.
Spoloènos Netscape v piatok vystavila na svojich stránkach ostrú verziu Netcastera - softvéru, ktorı umoòuje prijíma zo siete informácie cez tzv.
Netcaster je softvér vytvorenı v programovacom jazyku Jáva a Netscape sa s jeho vydaním omeškal dva mesiace kvôli viacerım chybám, ktoré sa objavili v jávovskom softvéri prehliadaèa Communicator.
Podobnı nástroj je k dispozícii aj na tvorbu "Webtops", èo znamená uívate¾sky uspôsobené prostredie, ktoré mení tapetu osobného poèítaèa na interaktívny kanál.
Netscape oèakáva, e z webtopu sa stane nástroj pre vırobcov poèítaèov, aby si nad windows vytvárali svoju vlastnú obrazovku a pre podniky bude slúi ako ich vnútornı informaènı kanál.
Uvedenie ostrej verzie Netcastera sprevádza konkurenènı boj Netscape a Microsoftu o informaèné zdroje.
Netscape má cez Netcastera poskytova prístup k 700 informaènım kanálom.
Mnohé médiá na toto úsilie o vıluènos odpovedali tım, e sa rozhodli pre obe push technológie zároveò.
Ostrá verzia push klienta Microsoftu sa oèakáva koncom leta.
Microsoft a Marimba sa dohodli na prijatí štandardu, ktorı umoní softvérovú aktualizáciu cez Internet.
Štandard bude vyuíva "Open Software Description" formát a podporujú ho aj firmy Netscape a Lotus.
Obaja hlavní vırobcovia webovskıch prehliadaèov - firmy Microsoft i Netscape - musia reagova na ïalšiu odhalenú chybu svojho softvéru.
V tomto prípade sa tıka ich riešenia java virtual machine (JVM), softvéru, ktorı ako súèas prehliadaèov umoòuje zo serverov sahova malé programy napísané v programovacom jazyku Jáva, tzv.
Pod¾a bezpeènostnıch opatrení zakomponovanıch do jávovského softvéru by mal prehliadaè za pomoci appletov sahova len dáta z materského servera daného appletu.
Programátor Ben Mesander z Colorada však dokázal, e je moné, aby applet prinútil prehliadaè sahova dáta aj z iného servera.
To je porušenie bezpeènostnıch pravidiel JVM.
Potenciálne to môe znamena, e tvorca appletu prinúti prehliadaè, aby si stiahol dáta nevedno odkia¾ a nevedno akého charakteru.
Benovi Mesandrovi sa však podarilo dosiahnu len stiahnutie dát vo formáte obrázkov.
Aj napriek vlaòajšiemu nadšeniu nad programovacím jazykom Sun Microsystems, Jáva ešte vdy zaostáva za hlavnımi programovacími jazykmi.
Prieskum Forrester Research z mája tohto roku ukázal, e len 16 percent zo spoloèností, ktoré uviedli, e budú inštalova jávovské aplikácie, to naozaj urobilo.
Zo štúdie Zona Research vyplynulo, e 50 percent respondentov pochybuje o schopnosti Jávy bea nad všetkımi platformami.
"Odvetvie bezpochyby Jávu podporuje," vraví analytik Zona Research.
Trvali desaroèia, kım iné programovacie jazyky dosiahli vrchol svojej funkènosti.
Intel a SAP America, èo je americká zloka databázovej firmy SAP, budú spolu ponúka malım a stredne ve¾kım podnikom hardvér a softvér pre internetovskı obchod.
Nová spoloènos nazvaná Pandesic LLC ponúkne novı produkt v hodnote 20tisíc a 40tisíc dolárov zaloenı na serveroch Intela a zjednodušenej verzii systému Sap R/3.
Microsoft vystavil na svojich stránkach beta verziu HTML editora Front Page, ktorı je, ako predošlé verzie editora, vybavenı aj malım webovskım serverom.
Táto beta umoòuje editova napr.
Táto beta verzia by mala by funkèná do konca roka.
Inštalaènı balík má 22 MB.
V priebehu 24 hodín skupina administrátorov internetovskıch sietí zablokovala 80tisíc e-mailovıch zásielok.
Zúèastnené strany konfliktu pouívali vojnovı slovník.
No blokované sú aj zásielky, ktoré nie sú spamom.
Je to akoby ste hodili jadrovú bombu na mesto, pretoe viete, e tam ijú teroristi.
Vo vojenskej terminológii by sme povedali, e ide o prijate¾nú paralelnú stratu.
V USA zaloenı vırobca športovıch potrieb Prince Sports Group vyaduje právo na doménové meno Prince.
Firma má zaregistrovanú znaèku Prince v USA i vo Ve¾kej Británii.
Meno "Prince" však pouíva na sieti u od roku 1995 britská poèítaèová firma Prince Plc, ktorá si ho riadne zaregistrovala u internetovského registrátora domén Network Solutions Inc.
Anglickı sudca odmietol iados Prince Sports Group, aby sa Prince Plc vzdala sieového názvu, take súd zrejme prebehne v USA, kde bola tie podaná aloba.
"Rozhodnutie ukáe, ako starostlivo treba posudzova prípady, ktoré vznikajú na Internete," uviedol britskı právny špecialista na znaèky.
Vyplıva to z nedávneho prieskumu európskej poboèky preh¾adávacej sluby Yahoo!
Èo do frekvencie pouívania je Yahoo!
Toto tvrdenie podporila aj nemecká prieskumná organizácia Fittkau & Maass, pod¾a ktorej sluby Yahoo!
Obe spoloènosti chcú vytvori obsaného sprievodcu webovskım nakupovaním so zoznamom vyše 100tisíc predajcov.
